# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - yu.yan@intel.com
env:
  global:
    - WARNINGS_OK=false
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
  matrix:
    - TEST=catkin_lint
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ros-planning/moveit/master/moveit.rosinstall
      TEST_BLACKLIST=moveit_ros_perception

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - source .moveit_ci/travis.sh
